FROM node:18-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /workspace/apps/web
COPY pnpm-lock.yaml package.json .npmrc ./
RUN npm install -g pnpm && pnpm install
COPY . .
EXPOSE 3000
CMD ["pnpm", "dev"]