services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web_prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - graphql
    command: pnpm start

  graphql:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    container_name: graphql_prod
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    command: node dist/main.js