FROM node:18-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /workspace/apps/graphql
COPY pnpm-lock.yaml package.json .npmrc ./
RUN npm install -g pnpm && pnpm install
COPY . .
EXPOSE 4000
CMD ["pnpm", "start:dev"]