import NavBar from '@/components/navbar/NavBar';
import '../global.css';
import ClientLayout from './client-layout';
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap" rel="stylesheet" />


export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div >
      <ClientLayout>

        <NavBar />
        <div>
          {children}
        </div>
      </ClientLayout>
    </div>
  );
}